### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by Lukas-Roberts** [learn-co-curriculum/fewpjs-oo-method-types#2]
There is a grammatical error in the 'Define get Keyword in Javascript Class Context' section. 9th paragraph, first sentence reads '_If included in the constructor, **a** expensive process_.' Should be '_If included in the constructor, **an** expensive process_'

**Comment by sylwiavargas** [comment]
Thank you for your support in keeping our labs neat! We've fixed the typo.
